/* Based on the file generated by Payload, with a guard that shows a setup screen
   instead of a crash when the CMS isn't configured yet. */
import config from "@payload-config";
import "@payloadcms/next/css";
import type { ServerFunctionClient } from "payload";
import { handleServerFunctions, RootLayout } from "@payloadcms/next/layouts";
import React from "react";

import { importMap } from "./admin/importMap.js";
import "./custom.scss";
import { cmsConfigured } from "@/cms/env";
import { diagnose, cmsReady } from "@/cms/diagnose";
import { SetupScreen } from "@/cms/admin/SetupScreen";

type Args = { children: React.ReactNode };

const serverFunction: ServerFunctionClient = async function (args) {
  "use server";
  return handleServerFunctions({ ...args, config, importMap });
};

const isNextControlFlow = (e: unknown) => typeof (e as { digest?: unknown })?.digest === "string";

const Layout = async ({ children }: Args) => {
  if (!cmsConfigured() || !(await cmsReady())) return <SetupScreen checks={(await diagnose()).checks} />;
  try {
    return await RootLayout({ config, importMap, serverFunction, children });
  } catch (e) {
    if (isNextControlFlow(e)) throw e;
    console.error("[admin] Failed to start CMS:", e);
    return <SetupScreen checks={(await diagnose()).checks} />;
  }
};

export default Layout;
