/* Based on the file generated by Payload, with a guard that explains startup problems. */
import type { Metadata } from "next";
import config from "@payload-config";
import { RootPage, generatePageMetadata } from "@payloadcms/next/views";
import { importMap } from "../importMap";
import { cmsConfigured } from "@/cms/env";
import { diagnose, cmsReady } from "@/cms/diagnose";
import { SetupScreen } from "@/cms/admin/SetupScreen";

type Args = {
  params: Promise<{ segments: string[] }>;
  searchParams: Promise<{ [key: string]: string | string[] }>;
};

const isNextControlFlow = (e: unknown) => typeof (e as { digest?: unknown })?.digest === "string";

export const generateMetadata = async ({ params, searchParams }: Args): Promise<Metadata> => {
  if (!cmsConfigured() || !(await cmsReady())) return { title: "CMS setup | RedBlink", robots: { index: false } };
  try {
    return await generatePageMetadata({ config, params, searchParams });
  } catch {
    return { title: "CMS setup | RedBlink", robots: { index: false } };
  }
};

const Page = async ({ params, searchParams }: Args) => {
  if (!cmsConfigured() || !(await cmsReady())) return null; // the layout shows the setup screen
  try {
    return await RootPage({ config, params, searchParams, importMap });
  } catch (e) {
    if (isNextControlFlow(e)) throw e;
    console.error("[admin] Page failed:", e);
    return <SetupScreen checks={(await diagnose()).checks} standalone={false} />;
  }
};

export default Page;
